apiVersion: skaffold/v4beta2
kind: Config
build:
  local:
    push: false
  # googleCloudBuild:
  #   projectId: ticketing-dev-375910
  artifacts:
    # - image: us.gcr.io/ticketing-dev-375910/auth
    - image: bssughosh/auth
      context: auth
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: bssughosh/client
      context: client
      sync:
        manual:
          - src: "**/*.jsx"
            dest: .
          - src: "**/*.js"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: bssughosh/tickets
      context: tickets
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: bssughosh/orders
      context: orders
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: bssughosh/expiration
      context: expiration
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: bssughosh/payments
      context: payments
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - ./infra/k8s/*
deploy:
  kubectl: {}
