name: Tests

on:
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Tests for auth
        run: cd auth && npm install && npm run test:ci
      - name: Tests for orders
        run: cd orders && npm install && npm run test:ci
      - name: Tests for payments
        run: cd payments && npm install && npm run test:ci
      - name: Tests for tickets
        run: cd payments && npm install && npm run test:ci
