name: Tests

on:
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [auth, orders, payments, tickets]
    steps:
      - uses: actions/checkout@v3
      - name: Tests for ${{matrix.service}}
        run: cd ${{matrix.service}} && npm install && npm run test:ci
